[workspace]
members = ["specta", "specta-*", "tests"]
resolver = "2"

[workspace.lints.rust]
# unsafe_code = { level = "forbid", priority = -1 } # The `export` feature uses unsafe.
# missing_docs = { level = "warn", priority = -1 } # TODO: Enable this

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
unwrap_used = { level = "warn", priority = -1 }
panic = { level = "warn", priority = -1 }
todo = { level = "warn", priority = -1 }
panic_in_result_fn = { level = "warn", priority = -1 }
